name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'

    # Install dependencies
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    # Bump the minor version in package.json
    - name: Bump minor version
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        NEW_VERSION=$(node -p "require('semver').inc('$CURRENT_VERSION', 'minor')")
        echo "Bumping version from $CURRENT_VERSION to $NEW_VERSION"

        # Update package.json with the new version
        npm version $NEW_VERSION --no-git-tag-version
        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

    # Build the project
    - name: Build the project
      run: yarn build

    # Commit and push dist + version bump
    - name: Commit and push dist
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        # Add dist and package.json
        git add -f dist package.json
        git commit -m "chore: release v${{ env.VERSION }} [skip ci]"
        git tag "v${{ env.VERSION }}"
        git push origin main --tags

    # Create a tarball with only dist
    - name: Package dist folder
      run: |
        mkdir -p release
        tar -czf release/plumvillage-shared-v${{ env.VERSION }}.tar.gz -C dist .

    # Upload the tarball as a release asset
    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: "v${{ env.VERSION }}"
        name: "Release v${{ env.VERSION }}"
        body: "📦 Automated release of version v${{ env.VERSION }}"
        draft: false
        prerelease: false
        files: |
          release/plumvillage-shared-v${{ env.VERSION }}.tar.gz
